Am tuannq new feature activity intent
Asian-Mobile-Inc/Training-K2 pull request #25
Opened 2022-08-02 09:27 UTC by tuannq201

2022-08-04 03:02 UTC, huyhn30 requested changes
merge code

2022-08-05 01:50 UTC, huyhn30 requested changes

2022-08-05 09:24 UTC, huyhn30 requested changes
Check same bug again

2022-08-05 09:24 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/CaculatorActivity.java
> +            if (!validateForm()) {
if (!TextUtils.isEmpty(mEdtNumberOne.getText()) && !TextUtils.isEmpty(mEdtNumberTwo.getText())) {

} else {

}

2022-08-05 09:24 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +                                R.string.receive_from_login_facebook,
format code again

2022-08-05 09:24 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +        mUser = (User) getIntent().getSerializableExtra("user");
public static final String SEND_DATA_USER = "send_data_user";

mUser = getIntent().getSerializableExtra(SEND_DATA_USER);

2022-08-05 09:24 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +                                mUser.getmName(),
format code again

2022-08-05 09:24 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/InformationActivity.java
> +                mUser.setmName(mEdtName.getText().toString().trim());
where data College and hobby ?

2022-08-08 03:12 UTC, huyhn30 requested changes
check same bug

2022-08-08 03:12 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/CaculatorActivity.java
> +        mBtnSub.setOnClickListener(view -> {
mBtnSub.setOnClickListener(view -> {
             if (validateForm()) {
                  mNumberOne = Double.parseDouble(mEdtNumberOne.getText().toString());
                  mNumberTwo = Double.parseDouble(mEdtNumberTwo.getText().toString());
                  mResult = mNumberOne - mNumberTwo;
                  mTvResult.setText((getString(R.string.text_result, mResult)));
             }
         });

2022-08-08 03:12 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/CaculatorActivity.java
> +    private boolean validateForm() {
```
    private boolean validateForm() {
        mEdtNumberTwo.setError(null);
        boolean isValidForm = true;
        if (TextUtils.isEmpty(mEdtNumberOne.getText())) {
            mEdtNumberOne.setError(getString(R.string.error_number_empty));
            isValidForm = false;
        }
        if (TextUtils.isEmpty(mEdtNumberTwo.getText())) {
            mEdtNumberTwo.setError(getString(R.string.error_number_empty));
            isValidForm = false;
        }
        return isValidForm;
    }
```

2022-08-08 03:12 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +        Acount mAcount = new Acount();
Name Local Variable: acount
Name Global Variable: mAcount

2022-08-08 03:12 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +        Acount mAcount = new Acount();
Acount acount = (Acount) getIntent().getSerializableExtra(SEND_DATA_ACOUNT);

2022-08-08 04:24 UTC, taitqs commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +        try {
Why use try catch here?

2022-08-08 04:24 UTC, taitqs commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +        try {
Why use try catch here?

2022-08-09 02:03 UTC, huyhn30 requested changes
check again

2022-08-09 02:03 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/LoginActivity.java
> +                    Intent intent = new Intent(LoginActivity.this, HomePageActivity.class);
Fix

2022-08-09 02:03 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/LoginActivity.java
> +        mBtnLogin.setOnClickListener(new View.OnClickListener() {
use lambda

2022-08-09 02:03 UTC, huyhn30 commented on app/src/am_tuannq/com/example/asian1/issue1/HomePageActivity.java
> +        Acount acount = new Acount();
`Acount about = (Acount)getIntent().getSerializableExtra(SEND_DATA_ACOUNT);`

2022-08-09 03:18 UTC, huyhn30 approved these changes

2022-08-09 03:19 UTC, huyhn30 approved these changes

2022-08-09 03:19 UTC, merged