Am longlv new feature activity and intent
Asian-Mobile-Inc/Training-K2 pull request #29
Opened 2022-08-04 07:46 UTC by longlv81

2022-08-05 03:18 UTC, huyhn30 requested changes
fix again

2022-08-05 03:18 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/FacebookLoginActivity.java
> +                String result =
Use model send data

2022-08-05 03:18 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/PersonalInfoActivity.java
> +                sendInfoToActivity(setInfo);
use model

2022-08-05 09:49 UTC, huyhn30 requested changes
Check same bug again

2022-08-05 09:49 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +            if (getTextOne.equals("") || getTextTwo.equals("")) return;
```
if (!TextUtils.isEmpty(mEdtNumberOne.getText()) && !TextUtils.isEmpty(mEdtNumberTwo.getText())) {

} else {

}

```

Fix convention again

2022-08-05 09:49 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +            if (getTextOne.equals("") || getTextTwo.equals("")) return;
Same

2022-08-05 09:49 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +        bundle.putString("key_message", result);
```
public static final String SEND_DATA_RESULT = "send_data_result";

bundle.putString(SEND_DATA_RESULT, result);
```

2022-08-05 09:49 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/model/FacebookModel.java
> +    public String toString() {
remove

2022-08-05 09:49 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/model/PersonalInfoModel.java
> +    public String toString() {
remove

2022-08-08 03:44 UTC, huyhn30 requested changes
Check and fix same bug

2022-08-08 03:44 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +        mBtnPlus.setOnClickListener(view -> calculate("+"));
public static final String CALCULATE_PLUS  = "calculate_plus";

 mBtnPlus.setOnClickListener(view -> calculate(CALCULATE_PLUS));

2022-08-08 03:44 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +            case "+":
case CALCULATE_PLUS:

2022-08-08 03:44 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +        if (!TextUtils.isEmpty(mEdtNumberOne.getText())
```
if (!TextUtils.isEmpty(mEdtNumberOne.getText())&& !TextUtils.isEmpty(mEdtNumberTwo.getText())) {
         Double mGetNumberOne = Double.parseDouble(mEdtNumberOne.getText().toString());
         Double mGetNumberTwo = Double.parseDouble(mEdtNumberTwo.getText().toString());
         String setResult = getString(R.string.result);
         (...)
}
```

2022-08-08 03:44 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/FacebookLoginActivity.java
> +                "^(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[a-z\\d@$!%*?&]{8,}$");
wrong condition

2022-08-08 03:44 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/PersonalInfoActivity.java
> +                sendInfoToActivity(personalInfo.toString());
Show Wrong Result

2022-08-09 06:59 UTC, huyhn30 requested changes
Fix name again

2022-08-09 06:59 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +    public static final String CALCULATE_PLUS = "+";
public static final String CALCULATE_PLUS = "calculate_plus";

2022-08-09 07:22 UTC, huyhn30 requested changes
private static final String SEND_FACEBOOK_ACCOUNT = "send_account";

2022-08-09 07:22 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/CalculatorActivity.java
> +    public static final String SPACE = " ";
?

2022-08-09 07:22 UTC, huyhn30 commented on app/src/am_longlv/com/example/asian1/issue2andissue3/FacebookLoginActivity.java
> +    private static final String SEND_FACEBOOK_ACCOUNT = "send_account";
private static final String SEND_FACEBOOK_ACCOUNT = "send_facebook_account";

2022-08-11 03:19 UTC, taitqs commented on app/src/am_longlv/com/example/asian1/issue2andissue3/FacebookLoginActivity.java
> +        mEdtEmail.setOnFocusChangeListener((view, b) -> {
b?

2022-08-11 03:19 UTC, taitqs commented on app/src/am_longlv/com/example/asian1/issue2andissue3/FacebookLoginActivity.java
> +                            getString(R.string.password_error));
format code

2022-08-11 03:44 UTC, merged