commit
Asian-Mobile-Inc/Training-K2 pull request #36
Opened 2022-08-11 04:35 UTC by longlv81

2022-08-11 07:58 UTC, taitqs commented on app/src/am_longlv/com/example/asian1/issue4fragmentargument/TwoFragmentsActivity.java
> +        fragmentManager = getSupportFragmentManager();
FragmentManager fragmentManager = getSupportFragmentManager();

2022-08-11 07:58 UTC, taitqs commented on app/src/am_longlv/res/layout/activity_two_fragments.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Use constrainlayout

2022-08-11 07:58 UTC, taitqs commented on app/src/am_longlv/res/layout/activity_two_fragments.xml
> +        <Button
Fix

2022-08-12 04:01 UTC, huyhn30 requested changes
wrong condition issue:
Have color in background first time open -> Don't have color until click button
Wrong title when backstack

2022-08-15 02:21 UTC, huyhn30 approved these changes

2022-08-15 02:21 UTC, merged